---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../../components/namespace
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
#  - ./intel-device-plugin/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./nvidia/device-plugin/ks.yaml
  - ./reloader/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./spegel/ks.yaml
