apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-gluetun
stringData:
    auth.toml: ENC[AES256_GCM,data:T1q7rEzUb79c9bAUScpAcn3Mqo4w31kT2XjF3GHbU1ml392t4Bg+mxOAT2XS4CBRoxaRhgn+puoIF0kp6XA+jChIfG3KfnHf2tVth3gnOWmR5sWtilrkiq7PKY+5AGHpKRUPyuUTUB+4Fje9oO9M06p6Yx8w9j43WvG9qWbMJMBGaFWBnnkKy+5rgKCs7uZ0NFFUdKbiLXnT5RqSRtIaIVglfgsfJaihCXhWdmNoXN9PnuxHXH6WjrCzsiljZJyfvyPnO5tGWdyIu+2kphW8ftaFVxKn9wE9Q0ke8Mgo/VaNwB8JNQnvUFwPEl2vLMzFMpZKcEmn6y65jtRs+9Zm,iv:QhveObg1MpTXomD42EwLywF4z9qEFN+2MCmV1H3Y6ak=,tag:cAd0fjoYFLMg7IVHEwkopw==,type:str]
sops:
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeXZxRkpKa2Q0REJTUUVS
            WUgrRXN5Mm8wWldrbUNUOVkySzhocjlQdWxZCmFmNXNKMDZQZHNLRW9HNUlFbWM3
            TnNyNjdPU1Vzb1ZMc1VWdEI0S1NWVncKLS0tIDBYUXBWZXRVVWxRNVRURVg0QUdS
            Zk1zOU43Yk1jSFBCT3YwSmphOGNsNEEK2ALRt9iy4erVDb6lRHvNFH4YyiwkoUas
            oQs0rf2EKu+VeyTmOz6M/sVSiTUPekcs4HagXQqHhaFYL2+31yarOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T19:57:22Z"
    mac: ENC[AES256_GCM,data:RfaNZUjFL2IhUfQiXYsMhaGFEnDhCtuzcuSGcptJWhOdDVNxwoaTvtPOuD8R8N9H4tMdd4qEEIw3SyFvKEfWiP0ktcAlA1WjHinncSwjEYqy34YS1ZXQH3OS3DRUxoAFaajS82DY6igg1ZhUQeBsz1w99oAdU4KFsi/tAEoYxFI=,iv:NVzuSe2ZJBfe4UQkpcfi1TptobAlZjQIJVujXgQWp50=,tag:RTa/Rc6WER3xcVnDpDKorw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
