---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../../components/namespace
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  # Flux-Kustomizations
  - ./checkrr/ks.yaml
  - ./immich/ks.yaml
  - ./overseerr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyplex-watched/ks.yaml
  #- ./jellyseerr/ks.yaml
  - ./kavita/ks.yaml
  - ./komga/ks.yaml
  - ./navidrome/ks.yaml
  - ./plex/ks.yaml
  - ./stash/ks.yaml
  - ./tautulli/ks.yaml
  - ./wizarr/ks.yaml
