---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik-charts.yaml
  - ./bjw-s-charts.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./fairwinds-charts.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./external-secrets.yaml
  - ./node-feature-discovery.yaml
  - ./nvdp.yaml
  - ./nvidia.yaml
  - ./postfinance.yaml
  - ./spegel.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./k8s-gateway.yaml
