---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headlamp
  namespace: kube-system
spec:
  targetNamespace: flux-system
  interval: 1h
  path: ./kubernetes/apps/flux-system/headlamp
  postBuild:
    substitute:
      SUBDOMAIN: headlamp
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  retryInterval: 1m
  timeout: 5m
