---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app headlamp
  namespace: kube-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: authentik
    - name: external-secrets-bitwarden
  interval: 1h
  path: ./kubernetes/apps/flux-system/headlamp/app
  postBuild:
    substitute:
      SUBDOMAIN: headlamp
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  wait: false # no flux ks dependents
  retryInterval: 1m
  timeout: 5m
