apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-plugin-config
data:
  config.yaml: |
    sharing:
      timeSlicing: {}
    resources:
      gpus:
        - name: skeelz.net/gpu  # Custom unified name
          devices: all
