---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unify-gpu
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/gpu/unify/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  timeout: 3m
