---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../../components/namespace
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - ./bazarr/ks.yaml
  - ./byparr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./huntarr/ks.yaml
  - ./kapowarr/ks.yaml
  - ./lidarr/ks.yaml
  - ./metube/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./unpackerr/ks.yaml
