---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: echo
  interval: 1h
  path: ./kubernetes/apps/network/echo/app
  postBuild:
    substitute:
      SUBDOMAIN: echo
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
