---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gpu-plugins
  namespace: flux-system
resources:
  - gpu/nvidia-device-plugin/ks.yaml
  - gpu/intel-device-plugin/ks.yaml
  - gpu/unify/ks.yaml
