---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vymanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn: []
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      vymanager:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/tparker00/postgres-init
              tag: 16.10@sha256:bdbbdc21b2e33255a387eaa0b2ca8103dae78d04feb370f5df806aff3870170f
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: vymanager-secret
        containers:
          frontend:
            image:
              repository: ghcr.io/community-vyprojects/vymanager-frontend
              tag: beta@sha256:e0051d842ba07c18fd7e2d043204de3441aa37253cbf0056dcf8d2e18a3d83b1
            env:
              TZ: ${TIMEZONE}
              NODE_ENV: production
              VYMANAGER_ENV: production
              BETTER_AUTH_URL: "https://vymanager.${SECRET_DOMAIN}"
              NEXT_PUBLIC_APP_URL: "https://vymanager.${SECRET_DOMAIN}"
              NEXT_PUBLIC_API_URL: "https://api-vymanager.${SECRET_DOMAIN}"
            envFrom: *envFrom
          backend:
            image:
              repository: ghcr.io/community-vyprojects/vymanager-backend
              tag: beta@sha256:6191dca609b1854dafcac44bf8f58e4bd4d731f4fc10b97630042582f8427fdc
            env:
              TZ: ${TIMEZONE}
              FRONTEND_URL: "https://vymanager.${SECRET_DOMAIN}"
            envFrom: *envFrom
    service:
      main:
        controller: *app
        primary: true
        ports:
          http:
            port: &frontend_port 3000
      api:
        controller: *app
        ports:
          http:
            port: &backend_port 8000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - name: vymanager-main
                port: *frontend_port
        parentRefs:
          - name: envoy-internal
            namespace: network
      api:
        hostnames: ["api-{{ .Release.Name }}.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - name: vymanager-api
                port: *backend_port
        parentRefs:
          - name: envoy-internal
            namespace: network
