---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./exporters
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./headlamp/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kromgo/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./thanos/ks.yaml
