---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${CLAIM:-${APP}}"
  labels:
    app.kubernetes.io/name: "${APP}"
spec:
  accessModes: ["${MFS_ACCESSMODES:-ReadWriteOnce}"]
  resources:
    requests:
      storage: "${MFS_CAPACITY}"
  storageClassName: moosefs-storage
