---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
resources:
  - ./claim.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: moosefs-csi
          namespace: storage
