---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bazarr-exporter/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./lidarr-exporter/ks.yaml
  - ./node-exporter/ks.yaml
  - ./radarr-exporter/ks.yaml
  - ./sabnzbd-exporter/ks.yaml
  - ./sonarr-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
