---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./books.yaml
  - ./downloads.yaml
  - ./immich.yaml
  - ./minio.yaml
  - ./movies.yaml
  - ./movies4k.yaml
  - ./music.yaml
  - ./photos.yaml
  - ./postgres-backup.yaml
  - ./qb.yaml
  - ./sabnzbd.yaml
  - ./stash.yaml
  - ./tv.yaml
